name: Setup
description: Setup of the needed software

inputs:
  os:
    description: The os for the run.
    required: true

  cxx-standard:
    description: The c++ standard used with the run.
    required: true

  ccache-variant:
    description: The ccache variant to use with the ccache-action
    required: true

runs:
  using: composite
  steps:
    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.os }}-${{ github.job }}-${{ inputs.cxx-standard }}
        restore-keys: ${{ inputs.os }}-
        variant: ${{ inputs.ccache-variant }}

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install ninja-build

    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install ninja

    - name: Setup Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install -y ninja

    - name: Set up Visual Studio shell on Windows
      uses: egor-tensin/vs-shell@v2
      if: runner.os == 'Windows'
      with:
        arch: x64
