name:
  cmake-and-ctest
description:
  Builds the project and tests it using cmake and ctest

inputs:
  os:
    description: The os for the run.
    required: true

  cc:
    description: The c compiler to use.
    required: true

  cxx:
    description: The c++ compiler to use.
    required: true

  cxx-standard:
    description: The c++ standard used with the run.
    required: true

  ccache-variant:
    description: The ccache variant to use with the ccache-action
    required: true

runs:
  using: composite
  steps:
    - name: Configure CMake and Build
      env:
        CC: ${{ inputs.cc }}
        CXX: ${{ inputs.cxx }}
        CMAKE_CONFIG_TYPE: Release
        CMAKE_GENERATOR: Ninja
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ inputs.ccache-variant }}
      shell: bash
      run: |
        cmake --version
        cmake -S . -B ./build -DRKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_CXX_STANDARD=${{ inputs.cxx-standard }} -L
        cmake --build ./build -v

    - name: Test
      env:
        CMAKE_CONFIG_TYPE: Release
      working-directory: ./build
      shell: bash
      run: |
        ctest --extra-verbose
