name: cmake-and-ctest
description: Builds the project and tests it using cmake and ctest

inputs:
  os:
    description: The os for the run.
    required: true

  cxx-standard:
    description: The c++ standard used with the run.
    required: true

  compiler:
    description: The compiler to use.
    required: true

runs:
  using: composite
  steps:
    - name: Setup needed software
      id: setup
      uses: ./.github/actions/setup
      with:
        os: ${{ inputs.os }}
        cxx-standard: $${{ inputs.cxx-standard }}

    - id: determine-preset
      shell: bash
      run: |
        echo "preset=${{ ( (runner.os == 'Windows') && 'windows-mscv' ) || format('{0}-{1}', runner.os, inputs.compiler ) }}-release-ninja" | tr "[:upper:]" "[:lower:]" >> $GITHUB_OUTPUT

    - name: Configure CMake and Build
      env:
        preset: ${{ steps.determine-preset.outputs.preset }}
        ccache-variant: ${{ steps.setup.outputs.ccache-variant }}
      shell: bash
      run: |
        cmake --version
        cmake --preset $preset -DCMAKE_CXX_STANDARD=${{ inputs.cxx-standard }} -DCMAKE_CXX_COMPILER_LAUNCHER=$ccache-variant
        cmake --build --preset $preset -v

    - name: Test
      env:
        preset: ${{ steps.determine-preset.outputs.preset }}
      shell: bash
      run: |
        ctest --preset $preset
