name:
  cmake-and-ctest
description:
  Builds the project and tests it using cmake and ctest

inputs:
  os:
    description: The os for the run.
    required: true

  cxx-standard:
    description: The c++ standard used with the run.
    required: true

  compiler:
    description: The compiler to use.
    required: true

  compiler-version:
    description: The compiler version to use.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup needed software
      id: setup
      uses: ./.github/actions/setup
      with:
        os:           ${{ inputs.os }}
        cxx-standard: ${{ inputs.cxx-standard }}

    - name: Get C and CXX compiler
      id: cxx-compiler
      uses: ./.github/actions/get-cxx-compiler
      with:
        compiler:         ${{ matrix.compiler }}
        compiler-version: ${{ matrix.compiler-version }}

    - name: Configure CMake and Build
      env:
        RKE_COMPILE_WARNING_AS_ERROR:   ON
        CMAKE_C_COMPILER:               ${{ steps.cxx-compiler.outputs.c-compiler }}
        CMAKE_CXX_COMPILER:             ${{ steps.cxx-compiler.outputs.cxx-compiler }}
        CMAKE_CXX_STANDARD:             ${{ inputs.cxx-standard }}
        CMAKE_BUILD_TYPE:               Release
        CMAKE_CXX_COMPILER_LAUNCHER:    ${{ steps.setup.outputs.ccache-variant }}
      shell: bash
      run: |
        env | sort
        cmake --version
        cmake -S . -B ./build -G Ninja
        cmake --build ./build -v

    - name: Test
      env:
        preset: ${{ steps.determine-preset.outputs.preset }}
      working-directory: ./build
      shell: bash
      run: |
        ctest -C Release --extra-verbose
