name:
  get-cmake_cxx_compiler-variable
description:
  Gets the CC and CXX environment variables.

inputs:
  compiler:
    description: The compiler to use.
    required: true

  compiler-version:
    description: The compiler version to use.
    required: true

outputs:
  cc:
    description: The c compiler
    value: ${{ steps.determine-compiler-variable.outputs.cc }}

  cxx:
    description: The c++ compiler
    value: ${{ steps.determine-compiler-variable.outputs.cxx }}

runs:
  using: composite
  steps:
    - name: determine-compiler-variable
      shell: bash
      run: |
        if [ "${{ inputs.compiler }}" = "clang" ]
        then
          echo "cc=clang-${{ inputs.compiler-version }}" >> $GITHUB_OUTPUT
          echo "cxx=clang++-${{ inputs.compiler-version }}" >> $GITHUB_OUTPUT
        elif [] 

