name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

env:
  BUILD_PATH: ./build

jobs:
  cmake-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          [
            { os: macos-11,     cc: clang,    cxx: clang++ },
            { os: macos-12,     cc: clang,    cxx: clang++ },

            { os: ubuntu-20.04, cc: clang-10, cxx: clang++-10 },
            { os: ubuntu-20.04, cc: clang-11, cxx: clang++-11 },
            { os: ubuntu-20.04, cc: clang-12, cxx: clang++-12 },

            { os: ubuntu-22.04, cc: clang-12, cxx: clang++-12 },
            { os: ubuntu-22.04, cc: clang-13, cxx: clang++-13 },
            { os: ubuntu-22.04, cc: clang-14, cxx: clang++-14 },

            { os: ubuntu-20.04, cc: gcc-9,    cxx: g++-9 },
            { os: ubuntu-20.04, cc: gcc-10,   cxx: g++-10 },

            { os: ubuntu-22.04, cc: gcc-9,    cxx: g++-9 },
            { os: ubuntu-22.04, cc: gcc-10,   cxx: g++-10 },
            { os: ubuntu-22.04, cc: gcc-11,   cxx: g++-11 },
            { os: ubuntu-22.04, cc: gcc-12,   cxx: g++-12 },

            { os: windows-2019, cc: cl,       cxx: cl },
            { os: windows-2022, cc: cl,       cxx: cl }
          ]
        cxx-standard: [ 17, 20 ]

    runs-on: ${{ matrix.settings.os }}

    steps:
      - uses:                           actions/checkout@v3

      - name:                           Setup needed software
        id:                             setup
        uses:                           ./.github/actions/setup
        with:
          os:                           ${{ matrix.settings.os }}
          cxx:                          ${{ matrix.settings.cxx }}

      - name: Configure CMake and Build
        env:
          CC:                           ${{ matrix.settings.cc }}
          CXX:                          ${{ matrix.settings.cxx }}
          CMAKE_CONFIG_TYPE:            Release
          CMAKE_GENERATOR:              Ninja
          CMAKE_CXX_COMPILER_LAUNCHER:  ${{ steps.setup.outputs.ccache-variant }}
        run: |
          cmake --version
          cmake -S . -B $BUILD_PATH -DRKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -L
          cmake --build $BUILD_PATH --verbose

      - name: CTest
        env:
          CMAKE_CONFIG_TYPE: Release
        working-directory: $BUILD_PATH
        run: |
          ctest --version
          ctest --extra-verbose
