name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [ macos-latest, ubuntu-latest, windows-2022 ]
        cxx-standard: [ 17, 20 ]
        preset: [ linux-clang-release-ninja, linux-gcc-release-ninja, macos-clang-release-ninja, windows-mscv-release-ninja ]
        exclude:
          - os: macos-latest
            preset: linux-clang-release-ninja
          - os: macos-latest
            preset: linux-gcc-release-ninja
          - os: macos-latest
            preset: windows-mscv-release-ninja
          - os: ubuntu-latest
            preset: macos-clang-release-ninja
          - os: ubuntu-latest
            preset: windows-mscv-release-ninja
          - os: windows-2022
            preset: linux-clang-release-ninja
          - os: windows-2022
            preset: linux-gcc-release-ninja
          - os: windows-2022
            preset: macos-clang-release-ninja

        include:
          - os: macos-latest
            CMAKE_CXX_COMPILER_LAUNCHER: ccache
            setup: |
              brew install ccache ninja
            preconfigure-action:

          - os: ubuntu-latest
            CMAKE_CXX_COMPILER_LAUNCHER: ccache
            setup: |
              sudo apt update
              sudo apt install ninja-build
            preconfigure-action:

          - os: windows-2022
            CMAKE_CXX_COMPILER_LAUNCHER: sccache
            setup: |
              choco install -y ninja
            preconfigure-action: |
              & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ github.job }}-${{ matrix.build-type }}-${{ matrix.cxx-standard }}
          restore-keys: ${{ matrix.os }}-
          variant: ${{ matrix.CMAKE_CXX_COMPILER_LAUNCHER }}

      - name: Setup
        run: ${{ matrix.setup }}

      - name: Configure CMake and Build
        run: |
          ${{ matrix.preconfigure-action }}
          cmake --version
          cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.CMAKE_CXX_COMPILER_LAUNCHER }}
          cmake --build --preset ${{ matrix.preset }} -v

      - name: Test
        run: |
          ctest --preset ${{ matrix.preset }}