name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [ windows-2022, ubuntu-latest ]
        build-type: [ Release ]
        cxx-standard: [ 17, 20 ]

        include:
          - os: ubuntu-latest
            CMAKE_CXX_COMPILER_LAUNCHER: ccache
            setup: |
              sudo apt update
              sudo apt install ninja-build
            preconfigure-action:

          - os: windows-2022
            CMAKE_CXX_COMPILER_LAUNCHER: sccache
            setup: |
              choco install -y ninja
            preconfigure-action: |
              & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ github.job }}-${{ matrix.build-type }}-${{ matrix.cxx-standard }}
          restore-keys: ${{ matrix.os }}-
          variant: ${{ matrix.CMAKE_CXX_COMPILER_LAUNCHER }}

      - name: Setup
        run: ${{ matrix.setup }}

      - name: Configure CMake and Build
        run: |
          ${{ matrix.preconfigure-action }}
          cmake --version
          cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DRKE_COMPILE_WARNING_AS_ERROR=ON -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.CMAKE_CXX_COMPILER_LAUNCHER }}
          cmake --build ./build --config ${{ matrix.build-type }} -v

      - name: Test
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build-type }} --extra-verbose