name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [
          macos-latest,
          ubuntu-latest,
          windows-2022
        ]

        cxx-standard: [
          17,
          20
        ]

        preset: [
          macos-clang-release-ninja,
          linux-clang-release-ninja,
          linux-gcc-release-ninja,
          windows-mscv-release-ninja
        ]

        exclude:
          - os: macos-latest
            preset: linux-clang-release-ninja
          - os: macos-latest
            preset: linux-gcc-release-ninja
          - os: macos-latest
            preset: windows-mscv-release-ninja

          - os: ubuntu-latest
            preset: macos-clang-release-ninja
          - os: ubuntu-latest
            preset: windows-mscv-release-ninja

          - os: windows-2022
            preset: macos-clang-release-ninja
          - os: windows-2022
            preset: linux-clang-release-ninja
          - os: windows-2022
            preset: linux-gcc-release-ninja

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup needed software
        id: setup
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          cxx-standard: $${{ matrix.cxx-standard }}

      - name: Build and Test
        uses: ./.github/actions/cmake-and-ctest
        with:
          os: ${{ matrix.os }}
          cxx-standard: ${{ matrix.cxx-standard }}
          compiler: ${{ matrix.compiler }}
          ccache-variant: ${{ steps.setup.outputs.ccache-variant }}
