name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [
          macos-latest,
          ubuntu-latest,
          windows-2022
        ]

        cxx-standard: [
          17,
          20
        ]

        preset: [
          linux-clang-release-ninja,
          linux-gcc-release-ninja,
          macos-clang-release-ninja,
          windows-mscv-release-ninja
        ]

        exclude:
          - os: macos-latest
            preset: linux-clang-release-ninja
          - os: macos-latest
            preset: linux-gcc-release-ninja
          - os: macos-latest
            preset: windows-mscv-release-ninja

          - os: ubuntu-latest
            preset: macos-clang-release-ninja
          - os: ubuntu-latest
            preset: windows-mscv-release-ninja

          - os: windows-2022
            preset: linux-clang-release-ninja
          - os: windows-2022
            preset: linux-gcc-release-ninja
          - os: windows-2022
            preset: macos-clang-release-ninja

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup needed software
        uses: ./.github/actions/setup

      - name: Configure CMake and Build
        run: |
          cmake --version
          cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }}
          cmake --build --preset ${{ matrix.preset }} -v

      - name: Test
        run: |
          ctest --preset ${{ matrix.preset }}
