name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [ windows-2022, ubuntu-latest ]
        build-type: [ Release ]
        cxx-standard: [ 17, 20 ]
        warning-as-errors: [ ON ]

        include:
          - os: ubuntu-latest
            CMAKE_CXX_COMPILER_LAUNCHER: ccache
            setup: |
              sudo apt update
              sudo apt install ninja-build
            preconfigure-action: |

          - os: windows-2022
            CMAKE_CXX_COMPILER_LAUNCHER: sccache
            setup: |
              choco install -y ninja
            preconfigure-action: |
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Vc\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.3 || exit 1

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ github.job }}-${{ matrix.build-type }}-${{ matrix.build-type }}-${{ matrix.cxx-standard }}
          restore-keys: ${{ matrix.os }}-

      - name: Setup
        run: ${{ matrix.setup }}

      - name: Configure CMake
        run: |
          ${{ matrix.preconfigure-action }}
          cmake -S . -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DCMAKE_COMPILE_WARNING_AS_ERROR=${{ matrix.warning-as-errors }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.CMAKE_CXX_COMPILER_LAUNCHER }}

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }} -v

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{ matrix.build-type }} --extra-verbose