name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          [
            { os: macos-11,     cc: clang,    cxx: clang++ },
            { os: macos-12,     cc: clang,    cxx: clang++ },

            { os: ubuntu-20.04, cc: clang-10, cxx: clang++-10 },
            { os: ubuntu-20.04, cc: clang-11, cxx: clang++-11 },
            { os: ubuntu-20.04, cc: clang-12, cxx: clang++-12 },

            { os: ubuntu-22.04, cc: clang-12, cxx: clang++-12 },
            { os: ubuntu-22.04, cc: clang-13, cxx: clang++-13 },
            { os: ubuntu-22.04, cc: clang-14, cxx: clang++-14 },

            { os: ubuntu-20.04, cc: gcc-9,    cxx: g++-9 },
            { os: ubuntu-20.04, cc: gcc-10,   cxx: g++-10 },

            { os: ubuntu-22.04, cc: gcc-9,    cxx: g++-9 },
            { os: ubuntu-22.04, cc: gcc-10,   cxx: g++-10 },
            { os: ubuntu-22.04, cc: gcc-11,   cxx: g++-11 },
            { os: ubuntu-22.04, cc: gcc-12,   cxx: g++-12 },

            { os: windows-2019, cc: cl,       cxx: cl },
            { os: windows-2022, cc: cl,       cxx: cl }
          ]
        cxx-standard: [ 17, 20 ]

    runs-on: ${{ matrix.settings.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: ./.github/actions/cmake-and-ctest
        with:
          os: ${{ matrix.settings.os }}
          cc: ${{ matrix.settings.cc }}
          cxx: ${{ matrix.settings.cxx }}
          cxx-standard: ${{ matrix.cxx-standard }}
