name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        settings:
          [
            { os: macos-11,     cc: clang,    cxx: clang++ },
            { os: macos-12,     cc: clang,    cxx: clang++ },
            { os: ubuntu-22.04, cc: clang-14, cxx: clang++-14 },
            { os: windows-2022, cc: cl,       cxx: cl }
          ]
        cxx-standard: [ 17, 20 ]

    runs-on: ${{ matrix.settings.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: ./.github/actions/cmake-and-ctest
        with:
          os: ${{ matrix.settings.os }}
          cc: ${{ matrix.settings.cc }}
          cxx: ${{ matrix.settings.cxx }}
          cxx-standard: ${{ matrix.cxx-standard }}

#  macos-clang:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ macos-11, macos-12 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ clang ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
#          compiler-version: ${{ matrix.compiler-version }}
#
#  ubuntu-20_04-clang:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ ubuntu-20.04 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ clang ]
#        compiler-version: [ 10, 11, 12 ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
#          compiler-version: ${{ matrix.compiler-version }}
#
#  ubuntu-22_04-clang:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ ubuntu-22.04 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ clang ]
#        compiler-version: [ 12, 13, 14 ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
#          compiler-version: ${{ matrix.compiler-version }}
#
#  ubuntu-20_04-gcc:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ ubuntu-20.04 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ gcc ]
#        compiler-version: [ 9, 10 ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
#          compiler-version: ${{ matrix.compiler-version }}
#
#  ubuntu-22_04-gcc:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ ubuntu-22.04 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ gcc ]
#        compiler-version: [ 9, 10, 11, 12 ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
#          compiler-version: ${{ matrix.compiler-version }}
#
#  windows-msvc:
#    strategy:
#      fail-fast: false
#
#      matrix:
#        os: [ windows-2019, windows-2022 ]
#        cxx-standard: [ 17, 20 ]
#        compiler: [ clang, msvc ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build and Test
#        uses: ./.github/actions/cmake-and-ctest
#        with:
#          os: ${{ matrix.os }}
#          cxx-standard: ${{ matrix.cxx-standard }}
#          compiler: ${{ matrix.compiler }}
