name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os: [
          macos-latest,
          ubuntu-latest,
          windows-2022
        ]

        cxx-standard: [
          17,
          20
        ]

        preset: []

        include:
          - os: macos-latest
            preset: macos-clang-release-ninja

          - os: ubuntu-latest
            preset: linux-clang-release-ninja
          - os: ubuntu-latest
            preset: linux-gcc-release-ninja

          - os: windows-2022
            preset: windows-mscv-release-ninja

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup needed software
        id: setup
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          cxx-standard: $${{ matrix.cxx-standard }}

      - name: Configure CMake and Build
        run: |
          cmake --version
          cmake --preset ${{ matrix.preset }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx-standard }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ steps.setup.outputs.ccache-variant }}
          cmake --build --preset ${{ matrix.preset }} -v

      - name: Test
        run: |
          ctest --preset ${{ matrix.preset }}
