name: Build and Test with CMake and CTest

on:
  push: { }
  pull_request: { }

jobs:
  build-and-test:
    strategy:
      fail-fast: false

      matrix:
        os:           [ ubuntu-latest ]
        cxx-standard: [ 17, 20 ]
        compiler:     [ clang, gcc ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Build and Test
        uses: ./.github/actions/cmake-and-ctest
        with:
          os: ${{ matrix.os }}
          cxx-standard: ${{ matrix.cxx-standard }}
          compiler: ${{ matrix.compiler }}
