name: cpp-linter

on:
  push: { }
  pull_request: { }
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch: { }

permissions:
  contents: write
  pull-requests: write

jobs:
  cpp-linter:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '18'
          files-changed-only: false
          style: 'file'   # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          step-summary: true
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
